import { User } from '@stores/users/userType.ts';

export const Response: User = {
	nickname: 'Gus',
	handle: 'gocanto',
	name: 'Gustavo Ocanto',
	email: 'otnacog@example.com',
	profession: 'Software Engineer',
	salt: '8c403772-dd0f-4543-b26c-bc96747742f3',
	social: [
		{
			handle: '@gocanto',
			url: 'https://x.com/gocanto',
			description: 'Follow me in X.',
			name: 'x',
		},
		{
			handle: 'gocanto',
			url: 'https://www.youtube.com/@gocanto',
			description: 'Subscribe to my YouTube channel.',
			name: 'youtube',
		},
		{
			handle: 'gocanto',
			url: 'https://www.instagram.com/gocanto',
			description: 'Follow me in Instagram.',
			name: 'instagram',
		},
		{
			handle: 'gocanto',
			url: 'https://www.linkedin.com/in/gocanto/',
			description: 'Follow me in LinkedIn.',
			name: 'linkedin',
		},
		{
			handle: 'gocanto',
			url: 'https://github.com/gocanto',
			description: 'Follow me in GitHub.',
			name: 'github',
		},
	],
	experience: [
		{
			uuid: 'c17a68bc-8832-4d44-b2ed-f9587cf14cd1',
			company: 'Perx Technologies',
			employment_type: 'Full-Time',
			location_type: 'On-Site',
			position: 'Head of Engineering',
			start_date: 'June, 2024',
			end_date: 'April, 2025',
			summary:
				'Led and integrated cross-functional engineering teams (DevOps, Infrastructure, Data, Frontend, Backend, Support) across time zones, fostering open communication and accountability. Scaled team growth and operations from Singapore, optimized performance (database queries from 3 s to 800 ms; API calls from 2 s to 100 ms), implemented cloud cost savings, and partnered with C-level leaders to expand engineering initiatives.',
			country: 'Singapore',
			city: 'Singapore',
			skills: 'Executive Leadership, Strategic Planning, Engineering Management, Cross-functional Team Leadership, Technical Architecture.',
		},
		{
			uuid: '99db1ca0-948e-40b1-984f-e3b157a5d336',
			company: 'Aspire',
			employment_type: 'Full-Time',
			location_type: 'On-Site',
			position: 'Senior Software Engineer & Manager',
			start_date: 'January, 2022',
			end_date: 'April, 2024',
			summary:
				'Led a 12-person APAC team overseeing the software development lifecycle, mentorship, technical direction, and system architecture design. Engineered critical financial systems—prioritized payment request queues and automated credit schemas—and spearheaded SEA wallets from architecture through integration, unifying payment workflows and ledger synchronization. Improved debit account balance queries for real-time access and boosted API response times. Resolved data inconsistencies, refactored code for reliability, designed flexible scheduled payment solutions, and directed the transition from a monolithic to microservices architecture, significantly enhancing platform scalability and maintainability.',
			country: 'Singapore',
			city: 'Singapore',
			skills: 'Leadership, Strategic Planning, Engineering Management, Cross-functional Team Leadership, Technical Architecture.',
		},
		{
			uuid: '01e33400-6957-4d16-8edb-0802a49e445e',
			company: 'BeMyGuest - Tours & Activities',
			employment_type: 'Full-Time',
			location_type: 'On-Site',
			position: 'Engineering Lead',
			start_date: 'September, 2017',
			end_date: 'November, 2021',
			summary:
				'Developed and maintained inventory systems with availability calculations and time-slot capacity management. Led SaaS platform development for auto-recurring subscription payments and invoicing. Owned integration of Adyen, Stripe, and PayPal gateways for new white-label e-commerce accounts, and implemented third-party booking supplier APIs across B2B, B2C, and white-label channels, supporting mission-critical operations in Southeast Asian markets.',
			country: 'Singapore',
			city: 'Singapore',
			skills: 'Leadership, Strategic Planning, Cross-functional Team Leadership, Engineering Management, Technical Architecture.',
		},
		{
			uuid: '1ba5d878-3c48-4d94-aded-4a4294c26e12',
			company: 'Freelance',
			employment_type: 'Contractor',
			location_type: 'Remote',
			position: 'Web Developer',
			start_date: 'June, 2014',
			end_date: 'September, 2017',
			summary:
				'Built diverse web applications for SMEs—including e-commerce, POS, medical history, and neighborhood feedback platforms—using PHP, Laravel, VueJS, and MySQL. I also designed and delivered a multi-city drop-shipment warehouse management system, enabling real-time inventory control linked to financial reporting and distribution across multiple locations.',
			country: 'United States',
			city: 'Oklahoma City',
			skills: 'Leadership, Strategic Planning, Strategy Alignment, Cross-functional Team Leadership, Complexity Management',
		},
		{
			uuid: '8501d986-144d-4f4d-bd3f-7fb066028142',
			company: 'Websarrollo',
			employment_type: 'Full-Time',
			location_type: 'On-Site',
			position: 'Founder & Software Engineer',
			start_date: 'February, 2011',
			end_date: 'May, 2014',
			summary:
				'Led a team of designers and PHP developers, managing nationwide client projects and overseeing the full app development lifecycle—including iOS/Android social networking apps. I built CMS, shipping-tracking, e-commerce, web portfolio, college enrollment, and university survey systems, plus a City Hall Administrative System covering accounts payable, HR, payroll, treasury, and tax modules. My work leveraged PHP, jQuery (and jQuery Mobile), Cordova-JS, MySQL, HTML5, AngularJS, and Laravel 5, integrating third-party APIs and Facebook/Twitter logins within a SCRUM framework.',
			country: 'Venezuela',
			city: 'Valencia',
			skills: 'Leadership, Strategic Planning, Strategy Alignment, Team Development, Complexity Management.',
		},
		{
			uuid: '82076e4e-6099-457f-8ed5-b10585125ce5',
			company: 'Encava',
			employment_type: 'Full-Time',
			location_type: 'On-Site',
			position: 'Web Developer',
			start_date: 'May, 2009',
			end_date: 'February, 2011',
			summary:
				'Maintained the company’s AS400 administrative system and spearheaded development of department-specific applications—an e-commerce inventory control for retail, web reporting for production-line quality control, an online appointment system for the medical department, and a visitor registration/management tool. I leveraged PHP, jQuery, MySQL, HTML5, and AS400 within a SCRUM framework.',
			country: 'Venezuela',
			city: 'Valencia',
			skills: 'Creative Problem Solving, Analytical Skills, Strategy Alignment, Strategic Planning, Complexity Management.',
		},
		{
			uuid: 'd8c3957c-99dd-401a-9d95-f2b6b1dc021a',
			company: 'ForjaCentro',
			employment_type: 'Full-Time',
			location_type: 'On-Site',
			position: 'Web Developer',
			start_date: 'March, 2008',
			end_date: 'April, 2009',
			summary:
				'Maintained a Visual Basic administrative system and built internal applications to streamline operations—mail management, mechanical design support, sales-report automation, and web-based customer invoicing. I trained staff on these tools and provided technical support for Windows 8 and PC servers using PHP, jQuery, MySQL, HTML, and SQL Server.',
			country: 'Venezuela',
			city: 'Valencia',
			skills: 'Creative Problem Solving, Analytical Skills, Strategy Alignment, Strategic Planning, Complexity Management.',
		},
	],
	projects:[
		{
			uuid: '00a0a12e-6af0-4f5a-b96d-3c95cc7c365c',
			language: 'PHP / Vue',
			title: 'Think of your energy as an invisible compass.',
			excerpt: 'After experiencing the highs and lows of going into business with a family member, I reached a significant turning point in my life.',
			url: 'https://github.com/aurachakra',
			created_at: '2023-02-25',
			updated_at: '2023-10-05',
		},
		{
			uuid: '00a0a12e-6af0-4f5a-b96d-3c95cc7c365c',
			language: 'Vue / TypeScript',
			title: 'Gus\'s personal website.',
			excerpt: 'Gus is a full-stack Software Engineer who has been building web technologies for more two decades.',
			url: 'https://github.com/gocantodev/client',
			created_at: '2021-11-03',
			updated_at: '2024-09-29',
		},
		{
			uuid: 'dc67854e-c8bd-4461-baba-8972bee7bfb5',
			language: 'GO',
			title: 'users-grpc-service',
			excerpt: 'users server & client communications service.',
			url: 'https://github.com/gocanto/users-grpc-service',
			created_at: '2022-04-17',
			updated_at: '2025-04-22',
		},
		{
			uuid: '32fd43ce-d957-4ad2-9d71-b57f71444f2a',
			language: 'PHP',
			title: 'laravel-simple-pdf',
			excerpt: 'Simple laravel PDF generator.',
			url: 'https://github.com/gocanto/laravel-simple-pdf',
			created_at: '2019-06-11',
			updated_at: '2020-12-26',
		},
		{
			uuid: 'b48d8098-962b-4ff9-884e-264ab33256c9',
			language: 'Vue / JS',
			title: 'vuemit',
			excerpt: 'The smallest Vue.js events handler.',
			url: 'https://github.com/gocanto/vuemit',
			created_at: '2017-02-01',
			updated_at: '2021-08-11',
		},
		{
			uuid: '19acd1d7-80ca-4828-88da-d3641f8d05e1',
			language: 'Vue / JS',
			title: 'google-autocomplete',
			excerpt: 'Google Autocomplete Vue Component.',
			url: 'https://github.com/gocanto/google-autocomplete',
			created_at: '2016-07-02',
			updated_at: '2021-08-11',
		},
		{
			uuid: '98b5d71a-1c78-4639-a9ed-343a8ba8c328',
			language: 'GO',
			title: 'converter-go',
			excerpt: 'Currency converter that\'s data-agnostic.',
			url: 'https://github.com/gocanto/go-converter',
			created_at: '2021-09-02',
			updated_at: '2021-10-11',
		},
		{
			uuid: '3ce8b01f-406a-474c-80f3-8426617b42fe',
			language: 'PHP',
			title: 'http-client',
			excerpt: 'Http client that handles retries, logging & dynamic headers.',
			url: 'https://github.com/gocanto/http-client',
			created_at: '2019-07-01',
			updated_at: '2022-12-22',
		},
		{
			uuid: 'e517a966-f7d0-46a1-9ee4-494b38a116e5',
			language: 'PHP',
			title: 'converter',
			excerpt: 'Immutable PHP currency converter that\'s data-agnostic.',
			url: 'https://github.com/gocanto/converter',
			created_at: '2019-06-07',
			updated_at: '2019-06-11',
		},
		{
			uuid: '928ac7e8-d0ba-4075-9c22-67050ab03755',
			language: 'PHP',
			title: 'Laravel Framework',
			excerpt: 'Contributions to the Laravel Framework.',
			url: 'https://github.com/laravel/framework/pulls?q=is%3Apr+is%3Aclosed+author%3Agocanto',
			created_at: '2017-07-06',
			updated_at: '2022-09-15',
		},
	],
	talks: [
		{
			uuid: 'b222d84c-5bbe-4c21-8ba8-a9baa7e5eaa9',
			title: 'Deprecating APIs',
			subject: 'PHP APIs',
			location: 'Singapore',
			created_at: '2019-02-11',
			updated_at: '2019-02-11'
		},
		{
			uuid: '249c50ad-2fd8-45af-a429-5e25d05a6bdd',
			title: 'Bootstrapping to Objects',
			subject: 'Systems design patters and conventions.',
			location: 'Singapore',
			created_at: '2018-12-04',
			updated_at: '2018-12-04'
		},
		{
			uuid: '36c88e42-b04d-4be1-a183-c53439468769',
			title: 'Restful Controllers in Laravel',
			subject: 'Actions abstractions in Laravel controllers.',
			location: 'Singapore',
			created_at: '2018-10-04',
			updated_at: '2018-10-04'
		},
	],
};
